services:
  - type: web
    name: fooddash
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: CI_ENVIRONMENT
        value: production
      - key: DATABASE_URL
        value: ""
      - key: DB_HOST
        value: ""
      - key: DB_PORT
        value: ""
      - key: DB_USER
        value: ""
      - key: DB_PASSWORD
        value: ""
      - key: DB_NAME
        value: ""
      - key: APP_BASE_URL
        value: ""
      - key: EMAIL_FROM
        value: ""
      - key: EMAIL_SMTP_HOST
        value: ""
      - key: EMAIL_SMTP_PORT
        value: ""
      - key: EMAIL_SMTP_USER
        value: ""
      - key: EMAIL_SMTP_PASS
        value: ""
      - key: EMAIL_SMTP_CRYPTO
        value: ""
      - key: AIVEN_CA_CERT
        value: ""

jobs:
  - name: migrate
    type: run
    dockerfilePath: ./Dockerfile
    plan: starter
    command: php spark migrate --all
    envVars:
      - key: CI_ENVIRONMENT
        value: production
      - key: DATABASE_URL
        value: ""
      - key: DB_HOST
        value: ""
      - key: DB_PORT
        value: ""
      - key: DB_USER
        value: ""
      - key: DB_PASSWORD
        value: ""
      - key: DB_NAME
        value: ""
      - key: AIVEN_CA_CERT
        value: ""