# Restore database from a backup file generated by db:backup.
param(
	[Parameter(Mandatory = $true)]
	[string]$File,
	[string]$ProjectRoot = "C:\xampp\htdocs\FoodDash"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if (-not (Test-Path -Path $ProjectRoot)) {
	throw "Project root was not found: $ProjectRoot"
}

Push-Location $ProjectRoot
try {
	& php spark db:restore --file=$File --by=script
	if ($LASTEXITCODE -ne 0) {
		throw "Database restore command failed with exit code $LASTEXITCODE"
	}
}
finally {
	Pop-Location
}
